---
all:
  children:
    lab_local:
      hosts:
        server-debian:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    proxmox_hosts:
      children:
        lab_local:
    proxmox_guests:
      hosts: {}
