services:
  caddy:
    image: ${CADDY_IMAGE:-caddy:2.11.4-alpine}
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8443:8443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/usr/share/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_proxy

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_proxy:
    name: caddy_proxy
